<a href="https://colab.research.google.com/github/deekshadaga/forsk_python/blob/master/numpy%2Cpandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Python Libraries for Data Science and Machine Learning
#Numpy - To process or compute n-dimensional mathematical datas
#Pandas - Used to access or process tabular or structured data
#MAtplotlib - Plotting or visualising the data value

In [0]:
import numpy as np
print(np.__version__)

1.18.2


In [0]:
a = np.array([[4,5,6,7,8],[2,7,8,4,2],[12,13,14,56,78]])
print(a)

[[ 4  5  6  7  8]
 [ 2  7  8  4  2]
 [12 13 14 56 78]]


In [0]:
#attributes
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 5)
15


In [0]:
a[1,1]

7

In [0]:
#Slicing
a

array([[ 4,  5,  6,  7,  8],
       [ 2,  7,  8,  4,  2],
       [12, 13, 14, 56, 78]])

In [0]:
#a[row_slicing , column slicing]
X = a[:,0:4]
X

array([[ 4,  5,  6,  7],
       [ 2,  7,  8,  4],
       [12, 13, 14, 56]])

In [0]:
Y = a[:,4:]
Y

array([[ 8],
       [ 2],
       [78]])

In [0]:
#.array
#.arange()
z = np.arange(36)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [0]:
#Shape manipulation  - .reshape()
z = z.reshape(3,4,3)
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [0]:
z[1:2,1:3,:]

array([[[15, 16, 17],
        [18, 19, 20]]])

In [0]:
z[1:3,:,:]

array([[[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [0]:
#concat or stacking
a

array([[ 4,  5,  6,  7,  8],
       [ 2,  7,  8,  4,  2],
       [12, 13, 14, 56, 78]])

In [0]:
b = np.array([0,1,2]).reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [0]:
np.hstack((a,b))

array([[ 4,  5,  6,  7,  8,  0],
       [ 2,  7,  8,  4,  2,  1],
       [12, 13, 14, 56, 78,  2]])

In [0]:
a

array([[ 4,  5,  6,  7,  8],
       [ 2,  7,  8,  4,  2],
       [12, 13, 14, 56, 78]])

In [0]:
c = np.arange(10).reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
np.vstack((a,c))

array([[ 4,  5,  6,  7,  8],
       [ 2,  7,  8,  4,  2],
       [12, 13, 14, 56, 78],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [0]:
a[:,-1]

array([ 8,  2, 78])

In [0]:
#Matrix Multiplication
a

array([[ 4,  5,  6,  7,  8],
       [ 2,  7,  8,  4,  2],
       [12, 13, 14, 56, 78]])

In [0]:
v = np.arange(5).reshape(5,1)
v

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [0]:
np.dot(a,v)

array([[ 70],
       [ 43],
       [521]])

In [0]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
a

array([[ 4,  5,  6,  7,  8],
       [ 2,  7,  8,  4,  2],
       [12, 13, 14, 56, 78]])

In [0]:
a
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.argmax(a))
print(np.argmin(a))
print(np.std(a))

226
78
2
15.066666666666666
14
5
21.056959788999826


In [0]:
#Pandas -- 10 mins of break
import pandas as pd

In [0]:
#DataFrame
#readcsv
c = ['a','b','c','d','e']
data = pd.DataFrame(a, columns = c)
data

a   b   c   d   e
0   4   5   6   7   8
1   2   7   8   4   2
2  12  13  14  56  78

In [0]:
data.loc[:,'c':'e'].max(axis=1)

0     8
1     8
2    78
dtype: int64

In [0]:
data.loc[:,'c':'e'].idxmax(axis=1)

0    e
1    c
2    e
dtype: object

In [0]:
ipl = pd.read_csv('matches.csv')
ipl

id  season       city  ...          umpire1          umpire2 umpire3
0      1    2017  Hyderabad  ...      AY Dandekar         NJ Llong     NaN
1      2    2017       Pune  ...   A Nand Kishore           S Ravi     NaN
2      3    2017     Rajkot  ...      Nitin Menon        CK Nandan     NaN
3      4    2017     Indore  ...     AK Chaudhary    C Shamshuddin     NaN
4      5    2017  Bangalore  ...              NaN              NaN     NaN
..   ...     ...        ...  ...              ...              ...     ...
631  632    2016     Raipur  ...   A Nand Kishore     BNJ Oxenford     NaN
632  633    2016  Bangalore  ...     AK Chaudhary  HDPK Dharmasena     NaN
633  634    2016      Delhi  ...        M Erasmus    C Shamshuddin     NaN
634  635    2016      Delhi  ...        M Erasmus        CK Nandan     NaN
635  636    2016  Bangalore  ...  HDPK Dharmasena     BNJ Oxenford     NaN

[636 rows x 18 columns]

In [0]:
#Total no. of matches
len(ipl)

636

In [0]:
#Which team had won by maximum run...?
ipl['win_by_runs'].idxmax(axis=0)

43

In [0]:
ipl.loc[43]['winner']

'Mumbai Indians'

In [0]:
#Which team had won by maximum wicket
ipl['win_by_wickets'].idxmax()

2

In [0]:
ipl.loc[2]['winner']

'Kolkata Knight Riders'

In [0]:
#Data filtering
#Compare operation
ipl[ipl['win_by_wickets'] == 10]['winner']

2            Kolkata Knight Riders
34                 Kings XI Punjab
71                 Deccan Chargers
119               Delhi Daredevils
183    Royal Challengers Bangalore
298               Rajasthan Royals
376                 Mumbai Indians
390            Chennai Super Kings
542    Royal Challengers Bangalore
590            Sunrisers Hyderabad
Name: winner, dtype: object

In [0]:
#%ge of mtches when batting first team won
          #%ge of matches when batting second team won
#team won by minimum runs
          #team won by minimum wicket
len(ipl[ipl['win_by_wickets'] == 0])/len(ipl)

0.4669811320754717

In [0]:
ipl[ipl['win_by_runs'] > 0]['win_by_runs'].min()

1

In [0]:
ipl[ipl['win_by_runs'] == 1]['winner']

58                  Mumbai Indians
105                Kings XI Punjab
163                Kings XI Punjab
344               Delhi Daredevils
350                 Mumbai Indians
518            Chennai Super Kings
598                  Gujarat Lions
614    Royal Challengers Bangalore
Name: winner, dtype: object

In [0]:
#How many seasons total played according to data set ?
#Which season as maximum no. of matches ?
      #Which team is most successfull
#What is the %ge of toss_winner when the team is also a winner?

In [0]:
len(ipl['season'].unique())

10

In [0]:
ipl['season'].value_counts().idxmax()

2013

In [0]:
len(ipl[ipl['winner'] == ipl['toss_winner']])/len(ipl)

0.5110062893081762

In [0]:
(ipl['winner'] == ipl['toss_winner']).sum()/len(ipl)

0.5110062893081762